spring:
  datasource:
    url: jdbc:mysql://localhost:3306/WebSocialPlatform
    username: root
    password: zckdemima123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/
  mail:
    host: smtp.qq.com
    username: ocingyou@foxmail.com
    password: grrpfmfipvundiia
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0